apiVersion: v1
kind: Pod
metadata:
  name: flask
  labels:
    app: task1
spec: 
  containers:
  - name: task1
    image: haideralam/task1kube
    ports:
    - containerPort: 5500
    

    kubectl run task1 --image=haideralam/task1kube