apiVersion: v1
kind: Pod
metadata:
  name: flask
  labels:
    app: task1
spec: 
  containers:
  - name: task1
    image: haideralam/task1kube
    ports:
    - containerPort: 5500
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: task1
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5500
    targetPort: 5500
